[package]
name = "example-atmega328p"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true

[profile.dev]
opt-level = 3
strip = true
overflow-checks = false
debug-assertions = false

[dependencies]
avr-bro = { path = "../../../avr-bro", features = ["atmega328p"] }